name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'yarn'

    - name: Install dependencies
      run: |
        echo "::group::apt install"
        sudo apt install fonttools fontforge python3-fontforge
        echo "::endgroup::"
        echo "::group::yarn install"
        yarn install
        echo "::endgroup::"

    - run: make

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: font
        path: 'build/Twemoji Mozilla.ttf'
