name: Build

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 18, 20, 22]
    steps:
    - uses: actions/checkout@v4
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'yarn'
    - name: Install dependencies
      run: |
        sudo apt install fonttools fontforge python3-fontforge
        yarn install
    - run: make
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: font
        path: 'build/Twemoji Mozilla.ttf'
