name: Font Build

on:
  workflow_dispatch:

jobs:
  font:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt -y update && sudo apt -y install fonttools fontforge python3-fontforge

    - name: Build font
      run: cd "$GITHUB_WORKSPACE" && npm install && make

    - name: Set current date and time as env variable
      id: scdntaev
      run: echo "date=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_OUTPUT

    - name: Archive artifacts
      uses: actions/upload-artifact@v3
      with:
        name: twemojicolr_win98sefork-${{steps.scdntaev.outputs.date}}
        path: ${{github.workspace}}/build/Twemoji Mozilla.ttf